# Generated by Django 5.0.4 on 2024-05-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistido.pessoa')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Físicas',
            },
            bases=('assistido.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrib.endereco')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assistido.pessoa')),
            ],
            options={
                'verbose_name': 'Pessoa/Endereço',
                'verbose_name_plural': 'Pessoas/Endereços',
                'db_table': 'assistido_pessoa_endereco',
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='enderecos',
            field=models.ManyToManyField(through='assistido.PessoaEndereco', to='contrib.endereco'),
        ),
        migrations.CreateModel(
            name='PessoaTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assistido.pessoa')),
                ('telefone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrib.telefone')),
            ],
            options={
                'verbose_name': 'Pessoa/Telefone',
                'verbose_name_plural': 'Pessoas/Telefones',
                'db_table': 'assistido_pessoa_telefone',
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefones',
            field=models.ManyToManyField(through='assistido.PessoaTelefone', to='contrib.telefone'),
        ),
    ]
